// Auto-generated from plan/SORU-BANKASI-TASLAK-v2.md for CatAIlyst

export type QuestionMode = 'individual' | 'corporate';

export type QuestionItem = {
  id: string;
  mode: QuestionMode;
  section: string;
  area: string;
  prompt: string;
  options: string[];
  reverse: boolean;
};

export const QUESTION_BANK: QuestionItem[] = [
  {
    id: 'B1.01',
    mode: 'individual',
    section: 'B1',
    area: 'K',
    prompt: "Bir dil modeli \"halüsinasyon\" ürettiğinde ne olmuştur?",
    options: ["Model eğitim verisindeki bir hatayı tekrarlamıştır", "Model, olgusal dayanağı olmayan bir içeriği yüksek güvenle üretmiştir", "Model isteği anlamadığı için rastgele kelime dizmiştir", "Modelin bağlam penceresi dolmuştur"],
    reverse: false,
  },
  {
    id: 'B1.02',
    mode: 'individual',
    section: 'B1',
    area: 'O',
    prompt: "Aynı soruyu aynı yapay zekâ aracına iki kez sorduğunuzda farklı cevaplar almanızın en olası sebebi nedir?",
    options: ["Model iki soru arasında yeniden eğitilmiştir", "Üretim sürecinde olasılıksal bir seçim vardır", "İnternet bağlantısı cevabı değiştirmiştir", "Soruyu yanlış yazmışsınızdır"],
    reverse: false,
  },
  {
    id: 'B1.03',
    mode: 'individual',
    section: 'B1',
    area: 'Z',
    prompt: "Bir modelin \"bilgi kesim tarihi\" (knowledge cutoff) neyi ifade eder?",
    options: ["Modelin abonelik süresinin bitişini", "Eğitim verisinin kapsadığı son tarihi", "Sohbetin silineceği tarihi", "Modelin güncelleneceği tarihi"],
    reverse: false,
  },
  {
    id: 'B1.04',
    mode: 'individual',
    section: 'B1',
    area: 'K',
    prompt: "Aşağıdakilerden hangisi üretken yapay zekânın yapamayacağı bir iştir?",
    options: ["Verdiğiniz metni özetlemek", "Kod yazmak", "Gelecekteki bir borsa fiyatını kesin olarak bilmek", "Farklı dilde metin üretmek"],
    reverse: false,
  },
  {
    id: 'B1.05',
    mode: 'individual',
    section: 'B1',
    area: 'K',
    prompt: "Bir sohbet asistanına soru sorduğunuzda modelin \"düşünme\" süreciyle ilgili en doğru ifade hangisidir?",
    options: ["Model, cevabı önce zihninde tasarlar sonra yazar", "Model, eğitiminde gördüğü örüntülere göre sıradaki kelimeyi olasılıkla seçer", "Model, internetten canlı cevap arar", "Model, soruyu bir uzmana iletir"],
    reverse: false,
  },
  {
    id: 'B1.06',
    mode: 'individual',
    section: 'B1',
    area: 'O',
    prompt: "\"Bağlam penceresi\" (context window) neyi sınırlar?",
    options: ["Modelin kaç farklı dil konuşabildiğini", "Modelin eğitim verisinin boyutunu", "Tek bir oturumda işleyebildiği toplam metin miktarını", "Modelin kaç kullanıcıya aynı anda hizmet verdiğini"],
    reverse: false,
  },
  {
    id: 'B1.07',
    mode: 'individual',
    section: 'B1',
    area: 'Z',
    prompt: "Bir model \"fine-tuning\" ile eğitildiğinde ne değişir?",
    options: ["Modelin tamamı sıfırdan yeniden eğitilir", "Modelin internet erişimi açılır", "Modelin mevcut bilgisi, ek veriyle belirli bir göreve uyarlanır", "Modelin lisansı değişir"],
    reverse: false,
  },
  {
    id: 'B2.01',
    mode: 'individual',
    section: 'B2',
    area: 'O',
    prompt: "Yapay zekâdan uzun bir raporu özetlemesini istiyorsunuz. Aşağıdaki isteklerden hangisi en kullanışlı çıktıyı verir?",
    options: ["\"Bu raporu özetle\"", "\"Bu raporu kısaca özetle\"", "\"Bu raporu, yönetim kuruluna sunmak üzere 5 maddede özetle; her maddede bir karar önerisi olsun\"", "\"Bu raporu profesyonelce özetle\""],
    reverse: false,
  },
  {
    id: 'B2.02',
    mode: 'individual',
    section: 'B2',
    area: 'K',
    prompt: "Son 30 günde yapay zekâyı işinizde kaç gün kullandınız?",
    options: ["Hiç", "1–5 gün", "6–15 gün", "16–25 gün", "Neredeyse her gün"],
    reverse: false,
  },
  {
    id: 'B2.03',
    mode: 'individual',
    section: 'B2',
    area: 'K',
    prompt: "Yapay zekâyı en çok hangi tür işte kullanıyorsunuz?",
    options: ["Metin yazma/düzenleme", "Özetleme", "Veri analizi", "Kod", "Görsel", "Araştırma", "Fikir üretme", "Çeviri", "Kullanmıyorum"],
    reverse: false,
  },
  {
    id: 'B2.04',
    mode: 'individual',
    section: 'B2',
    area: 'O',
    prompt: "Yapay zekâ kullanımınız iş akışınıza ne kadar yerleşmiş durumda?",
    options: ["Ara sıra merakla deniyorum, düzenli bir kullanımım yok", "Belirli işlerde kullanıyorum ama her seferinde sıfırdan başlıyorum", "Sık kullandığım istekleri saklıyorum, tekrar kullanıyorum", "Kendi şablonlarım/akışlarım var, işimin standart parçası", "Süreçlerimi yapay zekâ etrafında yeniden tasarladım, çıktıyı ölçüyorum"],
    reverse: false,
  },
  {
    id: 'B2.05',
    mode: 'individual',
    section: 'B2',
    area: 'O',
    prompt: "Yapay zekâya bir görev verdiniz, çıktı beklediğiniz gibi olmadı. Genelde ilk ne yaparsınız?",
    options: ["Aynı isteği tekrar gönderirim (1 p)", "İsteği daha detaylı ve örnekli yazarım (4 p)", "Görevi küçük adımlara bölerim (5 p)", "Vazgeçip elle yaparım (0 p)", "Başka bir araç denerim (3 p)"],
    reverse: false,
  },
  {
    id: 'B2.06',
    mode: 'individual',
    section: 'B2',
    area: 'O',
    prompt: "Yapay zekâdan bir e-postayı \"daha nazik\" yazmasını istiyorsunuz. Hangi istek en iyi sonucu verir?",
    options: ["\"Bunu daha nazik yaz\"", "\"Bunu yeniden yaz, daha kibar ol\"", "\"Bu e-postayı, alıcının yanlış anlamayacağı, resmî ama sıcak bir tonda yeniden yaz; gerekirse iki alternatif ver\"", "\"Bunu daha iyi yaz\""],
    reverse: false,
  },
  {
    id: 'B2.07',
    mode: 'individual',
    section: 'B2',
    area: 'O',
    prompt: "Son 30 günde, yapay zekâ çıktısını doğrudan kopyalayıp işinize koyduğunuz kaç örnek oldu?",
    options: ["Hiç", "1-5", "6-15", "16-30", "30+ *(sıklık arttıkça puan düşer: kör kopyalama riski)*"],
    reverse: false,
  },
  {
    id: 'B2.08',
    mode: 'individual',
    section: 'B2',
    area: 'Z',
    prompt: "Yapay zekâ kullanımınızı ekibinize nasıl aktarıyorsunuz?",
    options: ["Paylaşmıyorum, kişisel kalıyor", "Sorulunca gösteriyorum", "Slack/e-posta üzerinden örnekler paylaşıyorum", "Düzenli olarak ekip içi kısa oturumlar yapıyorum", "Ekibe yönelik resmî eğitim içeriği hazırladım"],
    reverse: false,
  },
  {
    id: 'B3.01',
    mode: 'individual',
    section: 'B3',
    area: 'O',
    prompt: "Son 30 günde, bir yapay zekâ çıktısını kullanmadan önce kaç kez bağımsız bir kaynaktan doğruladınız?",
    options: ["Hiç", "1–2 kez", "3–10 kez", "10+ kez", "Her seferinde"],
    reverse: false,
  },
  {
    id: 'B3.02',
    mode: 'individual',
    section: 'B3',
    area: 'O',
    prompt: "Yapay zekânın verdiği bir istatistiği rapora koyacaksınız. En doğru davranış hangisidir?",
    options: ["Model güvenilir görünüyorsa doğrudan kullanmak", "Modele \"bu doğru mu\" diye tekrar sormak", "Rakamın asıl kaynağını bulup oradan doğrulamak", "Başka bir modele sorup aynı cevabı alırsa kullanmak"],
    reverse: false,
  },
  {
    id: 'B3.03',
    mode: 'individual',
    section: 'B3',
    area: 'Z',
    prompt: "Bir yapay zekâ aracı size kaynak olarak bir akademik makale künyesi verdi. İlk yapmanız gereken nedir?",
    options: ["Künyeyi rapora eklemek", "Künyenin gerçekten var olduğunu bir veritabanından kontrol etmek", "Modele makalenin özetini sormak", "Yazarın adını aramak yeterli"],
    reverse: false,
  },
  {
    id: 'B3.04',
    mode: 'individual',
    section: 'B3',
    area: 'O',
    prompt: "Yapay zekâ çıktılarını doğrulama alışkanlığınızı nasıl tanımlarsınız?",
    options: ["Genelde olduğu gibi kullanırım", "Bir şey tuhaf görünürse kontrol ederim", "Önemli işlerde kontrol ederim", "Rakam, isim ve alıntı içeren her çıktıyı kontrol ederim", "Doğrulama adımı iş akışımın tanımlı bir parçası"],
    reverse: false,
  },
  {
    id: 'B3.05',
    mode: 'individual',
    section: 'B3',
    area: 'Z',
    prompt: "Yapay zekânın ürettiği bir görsel, gerçek bir fotoğraftan nasıl ayırt edilir?",
    options: ["YZ görselleri her zaman pikselli görünür", "Tek bir görselden kesin ayırt edilemez; el, yazı, ışık ve gölge gibi detaylara bakılır ama tek başına kesin kanıt değildir", "YZ görselleri renkli, fotoğraflar siyah-beyazdır", "YZ görselleri her zaman 4K'dır"],
    reverse: false,
  },
  {
    id: 'B3.06',
    mode: 'individual',
    section: 'B3',
    area: 'O',
    prompt: "Yapay zekâ size \"2025'te Türkiye'de e-ticaret pazarı 2,1 trilyon TL'ye ulaştı\" dedi. Siz bu rakamı hiç duymamıştınız. En doğru davranış?",
    options: ["Modele \"emin misin\" diye sormak (1 p)", "Rakamı kullanmak, model iyi bir kaynak (0 p)", "Rakamı arama motorundan bağımsız doğrulamak; bulunamazsa kullanmamak (5 p)", "Rakamı \"kaynak: yapay zekâ\" notuyla kullanmak (2 p)"],
    reverse: false,
  },
  {
    id: 'B4.01',
    mode: 'individual',
    section: 'B4',
    area: 'O',
    prompt: "Kurumsal bir sohbet asistanına şirket içi gizli bir sözleşmeyi yapıştırdınız. En doğru risk değerlendirmesi hangisidir?",
    options: ["Sohbet geçmişi silinirse veri tamamen ortadan kalkar", "Veri yalnızca sizin hesabınızda kalır, risk yoktur", "Sağlayıcının veri işleme koşullarına bağlıdır; kurumsal sözleşme yoksa veri saklanabilir veya eğitimde kullanılabilir", "Model veriyi ezberleyemez, bu yüzden gizlilik riski oluşmaz"],
    reverse: false,
  },
  {
    id: 'B4.02',
    mode: 'individual',
    section: 'B4',
    area: 'O',
    prompt: "Ekibinizden biri, müşteri şikâyetlerini yapay zekâyla özetleyip yönetime rapor ediyor. Özetlerin doğruluğu hiç kontrol edilmemiş. İlk hamleniz?",
    options: ["Örneklem alıp özetleri kaynakla karşılaştırmak (5 p)", "Kullanımı durdurup manuel sürece dönmek (3 p)", "Ekibe daha iyi istek yazmayı öğretmek (2 p)", "Sorun görmemek, çıktılar makul görünüyor (0 p)"],
    reverse: false,
  },
  {
    id: 'B4.03',
    mode: 'individual',
    section: 'B4',
    area: 'O',
    prompt: "İşe alım için gelen 200 CV'yi yapay zekâya eleyip kısa liste çıkarttınız. En önemli risk hangisidir?",
    options: ["Modelin CV'leri okuyamaması (1 p)", "Geçmiş veriye dayalı ayrımcılığın sisteme yerleşmesi ve fark edilmemesi (5 p)", "İşlemin uzun sürmesi (0 p)", "Adayların itiraz etmesi (2 p)"],
    reverse: false,
  },
  {
    id: 'B4.04',
    mode: 'individual',
    section: 'B4',
    area: 'K',
    prompt: "Kurumunuzun yapay zekâ kullanım politikasını okudunuz mu?",
    options: ["Politika olduğunu bilmiyorum", "Var ama okumadım", "Okudum", "Okudum ve uyguluyorum", "Hazırlanmasına katkı verdim"],
    reverse: false,
  },
  {
    id: 'B4.05',
    mode: 'individual',
    section: 'B4',
    area: 'O',
    prompt: "Yapay zekâyla ürettiğiniz bir görseli ticari kampanyada kullanacaksınız. Hangi konu netleştirilmeli?",
    options: ["Görselin çözünürlüğü", "Kullanılan aracın lisans koşulları ve ticari kullanım hakkı", "Görselin kaç saniyede üretildiği", "Modelin adı"],
    reverse: false,
  },
  {
    id: 'B4.06',
    mode: 'individual',
    section: 'B4',
    area: 'Z',
    prompt: "Bir müşteri, yapay zekâ destekli sisteminizin hakkında yanlış karar verdiğini iddia ediyor. Sistemin kararına itiraz yolu var mı?",
    options: ["İtiraz yolu yok, sistem kararı kesindir (0 p)", "Müşteriye \"sistem öyle hesapladı\" denir (1 p)", "İnsan inceleme ve itiraz süreci tanımlıdır; müşteriye nasıl başvuracağı söylenir (5 p)", "Kararı sessizce düzeltip müşteriye bildirilmez (2 p)"],
    reverse: false,
  },
  {
    id: 'B4.07',
    mode: 'individual',
    section: 'B4',
    area: 'Z',
    prompt: "Kurumunuz yapay zekâyla müşteri profili çıkarıyor. \"Önyargı\" (bias) riski en çok nereden doğar?",
    options: ["Modelin çok hızlı çalışmasından", "Eğitim verisindeki geçmiş eşitsizliklerin modele işlemesinden", "Müşterilerin profillemeye karşı çıkmasından", "Raporun çok uzun olmasından"],
    reverse: false,
  },
  {
    id: 'B5.01',
    mode: 'individual',
    section: 'B5',
    area: 'K',
    prompt: "Yapay zekâ konusundaki bilgi düzeyinizi nasıl değerlendirirsiniz?",
    options: ["Çok zayıf", "Zayıf", "Orta", "İyi", "Çok iyi"],
    reverse: false,
  },
  {
    id: 'B5.02',
    mode: 'individual',
    section: 'B5',
    area: 'K',
    prompt: "Yeni bir yapay zekâ aracıyla karşılaştığınızda ne hissedersiniz?",
    options: ["Uzak dururum, bana göre değil", "Merak ederim ama başlamakta zorlanırım", "Deneyerek öğrenirim", "Hızlı öğrenir, işime uyarlarım", "Öğrenip başkalarına da öğretirim"],
    reverse: false,
  },
  {
    id: 'B5.04',
    mode: 'individual',
    section: 'B5',
    area: 'O',
    prompt: "Bir yapay zekâ size çok kendinden emin bir cevap verdiğinde bu, cevabın doğru olma ihtimalini sizce nasıl etkiler?",
    options: ["Kendinden eminse muhtemelen doğrudur", "Genelde doğru olduğunu gösterir", "Fikrim yok", "Güven ile doğruluk ayrı şeylerdir", "Kendinden emin ton, doğruluk hakkında hiçbir bilgi vermez"],
    reverse: false,
  },
  {
    id: 'B5.05',
    mode: 'individual',
    section: 'B5',
    area: 'O',
    prompt: "Yapay zekâda yeni bir kavramla karşılaştığınızda ilk tepkiniz ne olur?",
    options: ["\"Bu benim işim değil\" diye geçerim", "Anlamasam da günlük işime devam ederim", "Kısa bir araştırma yaparım", "Bir eğitim/kaynak bulup öğrenirim", "Öğrenir ve ekibime aktarırım"],
    reverse: false,
  },
  {
    id: 'B5.06',
    mode: 'individual',
    section: 'B5',
    area: 'O',
    prompt: "Yapay zekâ konusunda geride kaldığınızı düşünüyor musunuz?",
    options: ["Hiç düşünmüyorum", "Nadiren", "Bazen", "Sık sık", "Sürekli *(yüksek kaygı, eğitimde özel ilgi gerektirir)*"],
    reverse: false,
  },
  {
    id: 'B6.01',
    mode: 'individual',
    section: 'B6',
    area: 'O',
    prompt: "Son 3 ayda yapay zekâ kullanarak yaptığınız bir işi, eskiden ne kadar sürdüğüyle karşılaştırdınız mı?",
    options: ["Hayır, ölçmedim", "Kabaca tahmin ettim", "Bir kez ölçtüm", "Birkaç kez ölçtüm", "Düzenli ölçüyorum"],
    reverse: false,
  },
  {
    id: 'B6.02',
    mode: 'individual',
    section: 'B6',
    area: 'K',
    prompt: "Son 6 ayda yapay zekâ konusunda bir eğitim, kurs veya yapılandırılmış öğrenme yaptınız mı?",
    options: ["Hayır", "Video izledim", "Kısa kurs", "Kapsamlı eğitim", "Sertifika programı"],
    reverse: false,
  },
  {
    id: 'B6.03',
    mode: 'individual',
    section: 'B6',
    area: 'O',
    prompt: "Yapay zekâ kullanımınızı ekip arkadaşlarınızla paylaşıyor musunuz?",
    options: ["Hayır", "Ara sıra sohbette", "Sorulduğunda gösteriyorum", "Düzenli paylaşıyorum", "Ekibe eğitim verdim"],
    reverse: false,
  },
  {
    id: 'B6.04',
    mode: 'individual',
    section: 'B6',
    area: 'O',
    prompt: "Yapay zekâ kullanırken karşılaştığınız sorunları nasıl çözüyorsunuz?",
    options: ["Çözemezsem bırakırım", "Etrafımdakilere sorarım", "İnternette ararım", "Deneme yanılmayla kendim çözerim", "Sistemli deneme yapar, öğrendiğimi kaydederim"],
    reverse: false,
  },
  {
    id: 'B6.05',
    mode: 'individual',
    section: 'B6',
    area: 'O',
    prompt: "Son 30 günde, yapay zekâ kullanımınızı bir iş sonucuna (zaman, maliyet, hata oranı) bağladınız mı?",
    options: ["Hiç bağlamadım", "Sezgisel olarak biliyorum", "Bir kez ölçtüm", "Birkaç kez ölçtüm", "Düzenli ölçüyorum"],
    reverse: false,
  },
  {
    id: 'B6.06',
    mode: 'individual',
    section: 'B6',
    area: 'K',
    prompt: "Kişisel hayatınızda (planlama, alışveriş, öğrenme, sağlık) yapay zekâ kullanıyor musunuz?",
    options: ["Hiç kullanmıyorum", "Nadiren", "Ayda birkaç kez", "Haftada birkaç kez", "Neredeyse her gün"],
    reverse: false,
  },
  {
    id: 'K1.01',
    mode: 'corporate',
    section: 'K1',
    area: 'O',
    prompt: "Kurumunuzun yapay zekâ hedefleri iş önceliklerine bağlı mı?",
    options: ["Net bir yapay zekâ hedefi yok, keşif aşamasındayız", "Ölçülebilir hedefler tanımlandı ve iş hedefleriyle hizalandı", "Uygulamalar hayata geçti, hedefe uygunluğu izleniyor", "Başarılı girişimler ölçekleniyor, hedefler sonuca göre güncelleniyor", "Değeri en üst düzeye çıkarmaya odaklı sürekli bir işleyiş var"],
    reverse: false,
  },
  {
    id: 'K1.02',
    mode: 'corporate',
    section: 'K1',
    area: 'O',
    prompt: "Üst yönetim yapay zekâ vizyonunu kuruma ne kadar net iletti?",
    options: ["Yönetimden yapay zekâ hakkında net bir iletişim yok", "Yönetim potansiyeli kabul ediyor ama vizyon paylaşılmadı", "Vizyon iletildi, ilk girişimler başladı", "Yönetim güçlü şekilde savunuyor, kurum genelinde anlaşıldı", "Yönetim öğrenme ve yenilik kültürünü aktif besliyor"],
    reverse: false,
  },
  {
    id: 'K1.03',
    mode: 'corporate',
    section: 'K1',
    area: 'O',
    prompt: "Yapay zekâ kullanım senaryolarınız (use case) hangi aşamada?",
    options: ["Tanımlanmış senaryo yok", "Fikirler var, önceliklendirme yapılıyor", "Onaylı senaryolar geliştiriliyor veya devreye alındı", "Başarılı olanlar başka departmanlara yayılıyor", "Senaryolar tanımlı metriklerle sürekli izleniyor"],
    reverse: false,
  },
  {
    id: 'K1.06',
    mode: 'corporate',
    section: 'K1',
    area: 'O',
    prompt: "Kurumunuzun yapay zekâ stratejisi bir dokümanda yazılı mı ve çalışanlar buna erişebiliyor mu?",
    options: ["Yazılı değil", "Yazılı ama gizli", "Var, kısmen paylaşılıyor", "Var, herkes erişiyor", "Var, düzenli güncelleniyor"],
    reverse: false,
  },
  {
    id: 'K2.01',
    mode: 'corporate',
    section: 'K2',
    area: 'O',
    prompt: "Yapay zekâ senaryolarınıza uygun veri kaynakları belirlendi mi?",
    options: ["Veri kaynakları konusunda sınırlı farkındalık var, tanımlı süreç yok", "Veri erişim planı hazırlanıyor", "Plan uygulanıyor; veri toplanıyor, temizleniyor, birleştiriliyor", "Veri yönetişim çerçevesi kurulu, ihtiyaç duyulan veri hazır", "Veri kalitesi ve erişilebilirliği sürekli izleniyor ve iyileştiriliyor"],
    reverse: false,
  },
  {
    id: 'K2.02',
    mode: 'corporate',
    section: 'K2',
    area: 'O',
    prompt: "Kurumsal verinizin yapay zekâ için kullanıma hazırlık düzeyi nedir?",
    options: ["Veri dağınık, çoğu farklı sistemlerde ve formatlarda", "Ana veri kaynakları biliniyor ama birleştirilmemiş", "Kritik veriler merkezî bir yerde toplandı", "Veri kataloğu ve sahiplik tanımlı", "Veri ürünleri tanımlı, kalite metrikleriyle izleniyor"],
    reverse: false,
  },
  {
    id: 'K2.03',
    mode: 'corporate',
    section: 'K2',
    area: 'O',
    prompt: "Kurumunuzda \"bu veriden kim sorumlu\" sorusunun net cevabı var mı?",
    options: ["Hiçbir veri için", "Birkaç veri için", "Kritik veriler için", "Çoğu veri için", "Tüm veri varlıkları için"],
    reverse: false,
  },
  {
    id: 'K2.04',
    mode: 'corporate',
    section: 'K2',
    area: 'Z',
    prompt: "Kişisel veri içeren verilerin yapay zekâda kullanımı için kurumunuzda net kural var mı?",
    options: ["Kural yok, herkes kendi inisiyatifiyle kullanıyor", "Sözlü uyarılar var ama yazılı değil", "Yazılı kural var", "Kural var, veri sınıflandırmasına bağlı", "Kural var, denetleniyor ve ihlal yaptırımı işliyor"],
    reverse: false,
  },
  {
    id: 'K2.05',
    mode: 'corporate',
    section: 'K2',
    area: 'Z',
    prompt: "Yapay zekâ projeniz için gereken verinin %70'i farklı departmanlarda, %30'u mevcut. En doğru yaklaşım?",
    options: ["%30 ile başlayıp beklentiyi düşürmek (3 p)", "Projeyi veri tamamlanana kadar ertelemek (2 p)", "Veri sahipleriyle anlaşıp kritik %30'u birleştirmek, eksik veriyi yönetilebilir aşamalara bölmek (5 p)", "Veriyi elle kopyalatmak (1 p)"],
    reverse: false,
  },
  {
    id: 'K3.01',
    mode: 'corporate',
    section: 'K3',
    area: 'O',
    prompt: "BT altyapınız yapay zekâ iş yüklerinin artışını karşılayabilir mi?",
    options: ["Mevcut yükü zor taşıyor", "Bugünkü ihtiyacı karşılıyor, büyümeye kapalı", "Kısmen ölçeklenebilir, kritik noktalarda darboğaz var", "Büyük ölçüde uyarlanabilir ve ölçeklenebilir", "Gelecekteki talep öngörülerek tasarlandı"],
    reverse: false,
  },
  {
    id: 'K3.02',
    mode: 'corporate',
    section: 'K3',
    area: 'O',
    prompt: "Yapay zekâ araçlarının mevcut sistemlerinizle entegrasyonu ne durumda?",
    options: ["Araçlar tamamen ayrı, elle veri taşınıyor", "Birkaç noktada elle bağlantı var", "Kritik entegrasyonlar kuruldu", "Çoğu iş akışında entegre", "Entegrasyon mimarisi tanımlı ve yönetiliyor"],
    reverse: false,
  },
  {
    id: 'K3.05',
    mode: 'corporate',
    section: 'K3',
    area: 'Z',
    prompt: "Kurumunuz üretken yapay zekâ çıktılarının kaydını (log) tutuyor mu?",
    options: ["Tutmuyor", "Kısmen, elle", "Otomatik loglama başladı", "Loglama + denetim erişimi var", "Loglama, denetim ve saklama politikası tanımlı"],
    reverse: false,
  },
  {
    id: 'K4.01',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Kurumunuzda yapay zekâ kullanımı için onaylanmış bir politika var mı?",
    options: ["Yazılı politika yok, herkes kendi bildiği gibi kullanıyor", "Politika hazırlanıyor ama yayımlanmadı", "Politika yayımlandı, çalışanların çoğu haberdar", "Politika yayımlandı, eğitimi verildi, ihlaller takip ediliyor", "Politika düzenli güncelleniyor, denetleniyor, yaptırımı işliyor"],
    reverse: false,
  },
  {
    id: 'K4.02',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Kurumda kullanılan yapay zekâ sistemlerinin envanteri tutuluyor mu?",
    options: ["Hangi araçların kullanıldığı bilinmiyor", "Kabaca biliniyor, kayıt yok", "Kısmi liste var", "Güncel envanter var", "Envanter risk sınıflandırmasıyla birlikte tutuluyor"],
    reverse: false,
  },
  {
    id: 'K4.03',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Yapay zekâ risklerinden kim sorumlu?",
    options: ["Tanımlı bir sorumlu yok", "Gayriresmî olarak BT'de", "Bir kişi/birim atandı", "Roller ve raporlama hattı yazılı", "Yönetim kurulu düzeyinde gözetim var"],
    reverse: false,
  },
  {
    id: 'K4.04',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Yapay zekâ kullanan çalışanlara yönelik eğitim/bilgilendirme yapıldı mı?",
    options: ["Hayır", "Bilgilendirme e-postası gönderildi", "Gönüllü eğitim sunuldu", "Zorunlu eğitim verildi", "Eğitim verildi, katılım ve etkinliği kayıt altında"],
    reverse: false,
  },
  {
    id: 'K4.05',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Kullandığınız yapay zekâ sağlayıcılarının veri işleme koşulları incelendi mi?",
    options: ["İncelenmedi", "Bir kısmı incelendi", "Kritik sağlayıcılar incelendi", "Tüm sağlayıcılar için değerlendirme yapıldı", "Değerlendirme düzenli tekrarlanıyor, sözleşmelere yansıtılıyor"],
    reverse: false,
  },
  {
    id: 'K4.06',
    mode: 'corporate',
    section: 'K4',
    area: 'Z',
    prompt: "Yapay zekâ kaynaklı bir olay/yanlış sonuç yaşandığında kurumunuzun prosedürü nedir?",
    options: ["Prosedür yok, olaylar kendiliğinden çözülüyor", "Olaylar konuşuluyor ama kayda geçmiyor", "Olay kaydı tutuluyor", "Kayıt + kök neden analizi yapılıyor", "Olay yönetimi, raporlama ve iyileştirme döngüsü tanımlı *(NIST Manage 4.1-4.3)*"],
    reverse: false,
  },
  {
    id: 'K4.07',
    mode: 'corporate',
    section: 'K4',
    area: 'O',
    prompt: "Kurumunuz yapay zekâ kullanımıyla ilgili düzenleyici gelişmeleri (AI Act, KVKK) takip ediyor mu?",
    options: ["Takip etmiyoruz", "Bireysel ilgi düzeyinde", "Bir kişi/birim sorumlu", "Düzenli izleme + yönetime raporlama var", "Uyum takvimi tanımlı ve uygulanıyor *(2 Ağustos 2026 denetim başlangıcı)*"],
    reverse: false,
  },
  {
    id: 'K5.01',
    mode: 'corporate',
    section: 'K5',
    area: 'O',
    prompt: "Yapay zekâ becerisi geliştirme kaynakları ne kadar erişilebilir?",
    options: ["Resmî bir program yok", "İhtiyaç kabul edildi, plan hazırlanıyor", "İlk eğitimler sunuluyor", "Kapsamlı program yürürlükte", "Sürekli öğrenme kültürü var, her seviyede destekleniyor"],
    reverse: false,
  },
  {
    id: 'K5.02',
    mode: 'corporate',
    section: 'K5',
    area: 'O',
    prompt: "Yapay zekâ projelerinde çalışan ekibin çeşitliliği nasıl?",
    options: ["Adanmış ekip yok", "İhtiyaç görüldü, ekip kuruluyor", "Başlangıç ekibi çalışıyor", "Farklı uzmanlıklardan güçlü ekip var", "Ekip kurum geneline yayılmayı aktif yönlendiriyor"],
    reverse: false,
  },
  {
    id: 'K5.03',
    mode: 'corporate',
    section: 'K5',
    area: 'O',
    prompt: "Kurumunuzda çalışanların yapay zekâ becerisi ölçüldü mü?",
    options: ["Hayır", "Anket yapıldı", "Öz-değerlendirme yapıldı", "Yapılandırılmış ölçüm yapıldı", "Düzenli ölçülüyor"],
    reverse: false,
  },
  {
    id: 'K5.04',
    mode: 'corporate',
    section: 'K5',
    area: 'Z',
    prompt: "Yapay zekâ becerisi, işe alım ve terfi değerlendirmelerinde dikkate alınıyor mu?",
    options: ["Hiç dikkate alınmıyor", "CV'lerde isteğe bağlı", "Bazı rollerde aranıyor", "Tanımlı yetkinlik olarak yer alıyor", "Rol tanımlarının standart parçası"],
    reverse: false,
  },
  {
    id: 'K5.05',
    mode: 'corporate',
    section: 'K5',
    area: 'O',
    prompt: "Kurumunuzda yapay zekâ konusunda \"resmî olmayan şampiyonlar\" (gönüllü öncüler) var mı?",
    options: ["Yok", "Birkaç kişi biliniyor ama desteklenmiyor", "Biliniyor ve takdir ediliyor", "Resmî olarak görevlendirildi", "Şampiyon ağı kurulmuş, düzenli toplanıyor"],
    reverse: false,
  },
  {
    id: 'K6.01',
    mode: 'corporate',
    section: 'K6',
    area: 'O',
    prompt: "Yapay zekâ benimsemesi için resmî bir değişim yönetimi planınız var mı?",
    options: ["Hayır", "Konuşuluyor", "Taslak hazırlandı", "Plan yürürlükte", "Plan uygulanıyor ve etkisi ölçülüyor"],
    reverse: false,
  },
  {
    id: 'K6.02',
    mode: 'corporate',
    section: 'K6',
    area: 'O',
    prompt: "Çalışanlar yapay zekâ kullanımını açıkça konuşabiliyor mu?",
    options: ["Kullanım gizli, çekiniliyor", "Bazıları kullanıyor ama söylemiyor", "Açıkça konuşuluyor", "Deneyimler paylaşılıyor", "Başarılar ve hatalar kurumsal olarak paylaşılıyor"],
    reverse: false,
  },
  {
    id: 'K6.03',
    mode: 'corporate',
    section: 'K6',
    area: 'O',
    prompt: "Yapay zekâ kaynaklı bir hata olduğunda ne oluyor?",
    options: ["Böyle bir durum yaşanmadı / bilmiyorum", "Kişi sorumlu tutuluyor", "Sorun çözülüyor, kayıt tutulmuyor", "Kayıt tutuluyor", "Kök neden analizi yapılıp süreç güncelleniyor"],
    reverse: false,
  },
  {
    id: 'K6.04',
    mode: 'corporate',
    section: 'K6',
    area: 'Z',
    prompt: "Yapay zekânın işleri değiştireceği konusu çalışanlarla nasıl konuşuluyor?",
    options: ["Hiç konuşulmuyor", "Dedikodu düzeyinde", "Yönetim bilgilendirme yaptı", "Düzenli iletişim + soru-cevap ortamı var", "Çalışanlar sürece dahil ediliyor, rollerin geleceği birlikte tasarlanıyor *(değişim yönetiminin olgun hâli)*"],
    reverse: false,
  },
  {
    id: 'K6.05',
    mode: 'corporate',
    section: 'K6',
    area: 'O',
    prompt: "Çalışanların yapay zekâ kullanımından duyduğu endişe (iş kaybı, kontrol) kurumda ölçülüyor mu?",
    options: ["Ölçülmüyor", "Yönetim sezgisel biliyor", "Bir kez anket yapıldı", "Düzenli anket var", "Anket + aksiyon döngüsü var *(endişe ölçülmezse direnç görünmez kalır)*"],
    reverse: false,
  },
  {
    id: 'K7.01',
    mode: 'corporate',
    section: 'K7',
    area: 'O',
    prompt: "Yapay zekâ yatırımlarınızın etkisini ölçüyor musunuz?",
    options: ["Ölçmüyoruz", "Sezgisel değerlendiriyoruz", "Bazı projelerde ölçüyoruz", "Tanımlı metriklerle ölçüyoruz", "Metrikler düzenli raporlanıyor ve karara giriyor"],
    reverse: false,
  },
  {
    id: 'K7.02',
    mode: 'corporate',
    section: 'K7',
    area: 'O',
    prompt: "Yapay zekâ senaryolarınız pilot aşamasını geçebiliyor mu?",
    options: ["Pilotlar başlıyor ama bitmiyor", "Pilotlar bitiyor, üretime geçmiyor", "Birkaçı üretime geçti", "Çoğu üretime geçiyor", "Pilottan üretime geçiş tanımlı bir süreç"],
    reverse: false,
  },
  {
    id: 'K7.03',
    mode: 'corporate',
    section: 'K7',
    area: 'O',
    prompt: "Yapay zekâ ile elde edilen kazanımı somut bir rakamla ifade edebiliyor musunuz?",
    options: ["Hayır", "Kabaca tahmin", "Bir proje için hesapladık", "Birkaç proje için", "Portföy düzeyinde raporluyoruz"],
    reverse: false,
  },
  {
    id: 'K7.04',
    mode: 'corporate',
    section: 'K7',
    area: 'Z',
    prompt: "Yapay zekâ yatırımları için tanımlı başarı kriterleri (KPI) var mı?",
    options: ["KPI yok", "Proje bazlı, yazılı değil", "Proje bazlı, yazılı", "Proje + kurum düzeyi KPI'lar var", "KPI'lar düzenli izleniyor, güncelleniyor, karara bağlanıyor"],
    reverse: false,
  },
  {
    id: 'K7.05',
    mode: 'corporate',
    section: 'K7',
    area: 'O',
    prompt: "Geçen yıl başlatılan yapay zekâ projelerinin kaçı bugün hâlâ üretimde?",
    options: ["Hiçbiri", "%25'ten azı", "Yaklaşık yarısı", "Çoğu", "Hepsi/neredeyse hepsi"],
    reverse: false,
  },
];